// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMk1fNcIk6OnP5EF9SRNGlNJbNtrvjGrc',
    appId: '1:832365674090:web:cd4a7f3af0c0544c2d1413',
    messagingSenderId: '832365674090',
    projectId: 'chat-app-da9ee',
    authDomain: 'chat-app-da9ee.firebaseapp.com',
    databaseURL: 'https://chat-app-da9ee-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-da9ee.appspot.com',
    measurementId: 'G-ECKPVLZZ6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBao4dfuWS9RxqoLils-wR_YXTDPRJarUg',
    appId: '1:832365674090:android:d3f08a5f11d869e82d1413',
    messagingSenderId: '832365674090',
    projectId: 'chat-app-da9ee',
    databaseURL: 'https://chat-app-da9ee-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-da9ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB-hVf1M03qSlbRl0izvsmgtZsPyDsLq0',
    appId: '1:832365674090:ios:84b0d84f1d4e2f322d1413',
    messagingSenderId: '832365674090',
    projectId: 'chat-app-da9ee',
    databaseURL: 'https://chat-app-da9ee-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-da9ee.appspot.com',
    iosClientId: '832365674090-vjq2olh38fstep0374f1ebc8pso55ftq.apps.googleusercontent.com',
    iosBundleId: 'com.example.meningDokonim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB-hVf1M03qSlbRl0izvsmgtZsPyDsLq0',
    appId: '1:832365674090:ios:84b0d84f1d4e2f322d1413',
    messagingSenderId: '832365674090',
    projectId: 'chat-app-da9ee',
    databaseURL: 'https://chat-app-da9ee-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-da9ee.appspot.com',
    iosClientId: '832365674090-vjq2olh38fstep0374f1ebc8pso55ftq.apps.googleusercontent.com',
    iosBundleId: 'com.example.meningDokonim',
  );
}
